### ISSUE TITLE
router5 v2.x

### ISSUE THREAD

**Issue by pho3nixf1re** [qur2/freezer-js-router5#1]
What is required for compatibility with router5 v2? The peer dependency only allows for 1.4.x currently. I'm new to router5 and am not sure what a dependency bump might require.

**Comment by qur2** [comment]
Oh thanks for pointing that out. I guess they bumped a major version in the
meantime. I'd just check with the tests if that still work fine. I'll try
to do it this weekend.

Cheers.

**Comment by qur2** [comment]
A quick run and all tests are failing. I checked the changelog, there were major changes to the plugin system: https://github.com/router5/router5/blob/master/CHANGELOG.md

I'll definitely get to that, though I cannot provide a timeframe.

**Comment by qur2** [comment]
Just released 0.4.0, tests are passing now.

**Comment by pho3nixf1re** [comment]
Wow! That was fast. I greatly appreciate you being on top of this. Rare in the OS community way too often.
